services:

  order-api-producer:
    build: ./order-api-producer/
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    networks:
      - rabbitmq_network
    depends_on:
      - rabbitmq



  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: spring_rabbitmq
    ports:
      - "5672:5672" # Puerto para RabbitMQ
      - "15672:15672" # Puerto para RabbitMQ Management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PWD}
    restart: always
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge